# Site configuration
# 1. Files excluded from Jekyll builds
# 2. Installed Gems
# 3. Gem settings
# 4. Jekyll settings
# 5. Collections
# 6. Jekyll collections settings
# 7. Site settings

# 1. Files excluded from Jekyll builds
exclude:
  - README.md
  - CODE_OF_CONDUCT.md
  - CONTRIBUTING.md
  - screenshot.png
  - LICENSE
  - CNAME
  - Gemfile
  - Gemfile.lock
  - garth-jekyll-theme.gemspec

# 2. Installed Gems
plugins:
  - jekyll-paginate
  - jekyll-seo-tag

# 3. Gem settings
paginate: 3 # jekyll-paginate > items per page
paginate_path: page:num # jekyll-paginate > blog page

# 4. Jekyll settings
sass:
  style: compressed # Style compression
permalink: pretty # Permalink style (/YYYY/MM/DD/page-name/)
excerpt_separator: <!-- more --> # Marks end of excerpt in posts
timezone: Europe/London # Timezone for blog posts and alike

# 5. Collections
collections:
  posts:
    title: Activation Point # Needed for Siteleaf
    output: true
    description: "Anecdotes about my experience building data-driven products.
     
      " # The post list page content


# 6. Jekyll collections settings
defaults:
  - scope:
      path: ""
      type: pages
    values:
      layout: page # Default layout
  - scope:
      path: ""
      type: posts
    values:
      layout: post # Default layout

# 7. Site settings
encoding: utf-8 # Make sure the encoding is right
title: "Omer BenA mi Consulting - data-driven insights for SaaS and consumer startups" # Site name or title
logo: "/assets/websiteLogo.png" # Site logo
# favicon: "/favicon.ico" # Uncomment to add custom favicon, or leave as is to use site logo
description: "Omer Ben Ami's personal consulting website" # Site description and default description
url: "https://www.omerbenami.com" # Site url
baseurl: ""
lang: en-GB
# more data for SEO and social preview (OpenGraph):
tagline: Anecdotes about my experience building data-driven products.
description: "Omer Ben Ami's personal consulting website."
twitter:
  username: omer_ben_ami
  card: summary



image: "/assets/websiteLogo.png" 
social:
  name: Omer Ben-Ami
  links:
    - https://twitter.com/Omer_ben_ami
    - https://www.youtube.com/channel/UCRRVYwJ-qt_5FbFVRId7BEg

